import {AndroidPermissions} from './android-permissions';
import {AppAvailability} from './app-availability';

export interface FullAndroidAppMarketData {
    physical_address?: string;
    short_desc?: string;
    app_availability?: AppAvailability;
    i18n_lang?: string[];
    price_i18n_countries?: string[];
    rating?: number;
    downloads_min?: number;
    description?: string;
    what_is_new?: string;
    title?: string;
    screenshots?: string[];
    cat_keys?: string[];
    market_source?: string;
    downloads?: string;
    permissions?: string[];
    price?: string;
    price_currency?: string;
    cat_int?: number;
    size?: number;
    iap?: boolean;
    iap_min?: number;
    iap_max?: number;
    content_rating?: string;
    lang?: string;
    email?: string;
    ratings_2?: number;
    similar?: string[];
    badges?: string[];
    interactive_elements?: string[];
    ratings_1?: number;
    price_numeric?: number;
    ratings_4?: number;
    ratings_3?: number;
    ratings_5?: number;
    created?: string;
    downloads_max?: number;
    cat_key?: string;
    version?: string;
    market_update?: string;
    cat_type?: number;
    package_name?: string;
    from_developer?: string[];
    category?: string;
    developer?: string;
    number_ratings?: number;
    icon?: string;
    icon_72?: string;
    privacy_policy?: string;
    featured_graphic?: string;
    min_sdk?: string;
    website?: string;
    promo_video?: string;
    market_status?: string;
    unpublished_timestamp?: string;
    market_url?: string;
    deep_link?: string;

}
