POST {{apiURL}}/forgot-pswd
Content-Type: application/json

{
  "email": "admin@email.com"
}

###
POST {{apiURL}}/change-pswd
Content-Type: application/json
Authorization: {{authHeader}}

{
  "password": "admin",
  "passwordConfirm" : "admin"
}