export const ROLE_READ = 'ROLE_READ';
export const ROLE_CREATE = 'ROLE_CREATE';
export const ROLE_UPDATE = 'ROLE_UPDATE';
export const ROLE_DELETE = 'ROLE_DELETE';

export const MASTER_ACCOUNT_READ = 'MASTER_ACCOUNT_READ';
export const MASTER_ACCOUNT_CREATE = 'MASTER_ACCOUNT_CREATE';
export const MASTER_ACCOUNT_UPDATE = 'MASTER_ACCOUNT_UPDATE';
export const MASTER_ACCOUNT_DELETE = 'MASTER_ACCOUNT_DELETE';
export const MASTER_ACCOUNT_BLOCK = 'MASTER_ACCOUNT_BLOCK';

export const ACCOUNT_READ = 'ACCOUNT_READ';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
