CREATE TYPE DB_OBJECTS AS ENUM ('ACCOUNT', 'ACCOUNT_TO_ROLE', 'AUTHORITY', 'ROLE', 'ROLE_TO_AUTHORITY', 'SERVICE_TYPE');

ALTER TABLE logger
    ALTER COLUMN db_object TYPE DB_OBJECTS USING db_object::DB_OBJECTS;

ALTER TABLE logger
    ALTER COLUMN old_val TYPE JSONB USING old_val::JSONB;

ALTER TABLE logger
    ALTER COLUMN new_val TYPE JSONB USING new_val::JSONB;

INSERT INTO version (version)
VALUES ('1.2.0-5');