package ru.mint.mobile.store.parser.service.dto

data class FullAndroidAppMarketData(
        var physical_address: String? = null,
        var short_desc: String? = null,
        var app_availability : AppAvailability? = null,
        var i18n_lang : List<String>? = null,
        var price_i18n_countries : List<String>? = null,
        var rating : String? = null, //Double? = 0.0,
        var downloads_min : String? = null, // : Long? = 0,
        var description : String? = null,
        var what_is_new : String? = null,
        var title : String? = null,
        var screenshots : List<String>? = null,
        var cat_keys : List<String>? = null,
        var market_source : String? = null,
        var downloads : String? = null,
        var permissions : MutableList<String>? = null,
        var price : String? = null,
        var price_currency : String? = null,
        var cat_int : String? = null, // : Int? = 0,
        var size : String? = null, // : Int? = 0,
        var iap : Boolean = false,
        var iap_min : String? = null, //Double? = 0.0,
        var iap_max : String? = null, //Double? = 0.0,
        var content_rating : String? = null,
        var lang : String? = null,
        var email : String? = null,
        var ratings_2 : String? = null, // : Int? = 0,
        var similar : List<String>? = null,
        var badges : List<String>? = null,
        var interactive_elements : List<String>? = null,
        var ratings_1 : String? = null, // : Int? = 0,
        var price_numeric : String? = null, //Double? = 0.0,
        var ratings_4 : String? = null, // : Int? = 0,
        var ratings_3 : String? = null, // : Int? = 0,
        var ratings_5 : String? = null, // : Int? = 0,
        var created : String? = null,
        var downloads_max : String? = null, // : Long? = 0,
        var cat_key: String? = null,
        var version : String? = null,
        var market_update : String? = null,
        var cat_type : String? = null, // : Int? = 0,
        var package_name : String? = null,
        var from_developer : List<String>? = null,
        var category : String? = null,
        var developer : String? = null,
        var number_ratings : String? = null, // : Int? = 0,
        var icon : String? = null,
        var icon_72 : String? = null,
        var privacy_policy : String? = null,
        var featured_graphic : String? = null,
        var min_sdk : String? = null,
        var website : String? = null,
        var promo_video : String? = null,
        var market_status : String? = null,
        var unpublished_timestamp : String? = null,
        var market_url : String? = null,
        var deep_link : String? = null
)