ALTER TABLE accounts_and_servers
    ADD COLUMN creation_date TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC') NOT NULL;

ALTER TABLE fb_accounts
    ADD COLUMN creation_date TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC') NOT NULL;

INSERT INTO version (version)
VALUES ('1.1.0-1');