package ru.mint.mobile.store.parser.repository.entity

enum class SettingName {
    SENDER_EMAIL,
    SENDER_PASSWORD,
    MAIL_SMTP_AUTH,
    MAIL_SMTP_STARTTLS_ENABLE,
    MAIL_SMTP_HOST,
    MAIL_SMTP_PORT,

    LUMINATI_USERNAME,
    LUMINATI_PSWD,
    LUMINATI_PROXY_PORT,
    LUMINATI_REQUEST_MAX_FAILURES,

    REMOVED_APP_ICON_URL,
    ITUNES_APP_URL_TEMPLATE,
    ANDROID_APP_URL_TEMPLATE,
    ANDROID_APP_URL_TEMPLATE_SIMPLE,
    ITUNES_APP_URL_TEMPLATE_SIMPLE,
//    IOS_TOP_APPS_URL,
//    ANDROID_TOP_APPS_URL,
    IOS_TOP_APPS_URL_TEMPLATE,
    ANDROID_TOP_APPS_URL_TEMPLATE,
    STORE_CATEGORIES_ANDROID,
    STORE_CATEGORIES_IOS,
    CHECK_CATEGORIES_ON_START,

    PARSING_DATA_UPDATE_INTERVAL,
    PARSE_TOP_INTERVAL,
    APPS_PINGER_INTERVAL,

    TOP_PARSER_ANDROID_MAIN_CONTAINER_KEY,
    TOP_PARSER_ANDROID_DESCRIPTION_KEY,
    TOP_PARSER_ANDROID_REVIEWS_KEY,
    TOP_PARSER_ANDROID_SCREENSHOTS_KEY,
    TOP_PARSER_ANDROID_TITLE_KEY,
    TOP_PARSER_ANDROID_ICON_URL_KEY,
    TOP_PARSER_ANDROID_CARDS_KEY,
    TOP_PARSER_ANDROID_APPID_IN_CARD_KEY,

    USE_LUMINATI_FOR_GET_TOP,
    ADMIN_EMAIL,
    WORDS_SEARCH_REGEX
}