package ru.mint.dao

enum class Authorities {
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    MASTER_ACCOUNT_READ,
    MASTER_ACCOUNT_CREATE,
    MASTER_ACCOUNT_UPDATE,
    MASTER_ACCOUNT_DELETE,
    MASTER_ACCOUNT_BLOCK,

    ACCOUNT_READ,
    ACCOUNT_CREATE,
    ACCOUNT_UPDATE
}